format = """
╭─\
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$cmd_duration\
$line_break\
╰\
$character"""

add_newline = false

[directory]
style = "bright-green"

[character]
success_symbol = "[λ](purple)"
error_symbol = "[λ](red)"
vimcmd_symbol = "[λ](green)"

[git_branch]
format = "[$symbol$branch]($style)"
style = "bright-red"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
symbol = " "
format = '\[[$symbol$virtualenv $version]($style)\]'
style = "bright-black"
